#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.2
#  in conjunction with Tcl version 8.6
#    Mar 03, 2020 07:53:26 PM +0200  platform: Windows NT

import sys
import time
from threading import Thread

import back
import kitchen
import order

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


def vp_start_gui(server):
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1(root)
    top.server = server
    update_thread = Update(top)
    update_thread.start()
    root.mainloop()
    return top


w = None


def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    # rt = root
    root = rt
    w = tk.Toplevel(root)
    top = Toplevel1(w)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Update(Thread):
    def __init__(self, gui):
        super(Update, self).__init__()
        self.gui = gui

    def run(self):
        while True:
            if self.gui.server is not None and self.gui.server.order_m is not None:
                with back.Server.wait_lock:
                    self.gui.wating_lst.delete(0, tk.END)
                    i = 0
                    for ord in self.gui.server.order_m.clone():
                        self.gui.wating_lst.insert(i, 'Order id: ' + str(ord[1])
                                                   + ' Priority: ' + str(order.Priority(ord[0])))
                        i += 1
                with kitchen.kitchen_lock:
                    self.gui.kitchen_lst.delete(0, tk.END)
                    self.gui.done_lst.delete(0, tk.END)
                    i = 0
                    for ord in self.gui.server.kitchen_obj.in_kitchen:
                        self.gui.kitchen_lst.insert(i, 'Order id: ' + str(ord))
                        i += 1

                    for ord in self.gui.server.kitchen_obj.done:
                        self.gui.done_lst.insert(i, 'Order id: ' + str(ord))
                        i += 1
            else:
                print('none')
            time.sleep(1)


class Toplevel1:

    def main(self):
        while True:
            self.update_wait_lst()
            time.sleep(1)

    def __init__(self, top=None):
        self.server = None
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        font10 = "-family {Segoe Print} -size 13"
        font9 = "-family {Tahoma} -size 10"

        top.geometry("1256x991+428+0")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.wating_lst = tk.Listbox(top)
        self.wating_lst.place(relx=0.032, rely=0.081, relheight=0.275
                              , relwidth=0.3)
        self.wating_lst.configure(background="white")
        self.wating_lst.configure(disabledforeground="#a3a3a3")
        self.wating_lst.configure(font=font9)
        self.wating_lst.configure(foreground="#ff0000")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.15, rely=0.04, height=23, width=152)
        self.Label1.configure(activeforeground="#000000")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Wating orders''')

        self.kitchen_lst = tk.Listbox(top)
        self.kitchen_lst.place(relx=0.032, rely=0.424, relheight=0.275
                               , relwidth=0.3)
        self.kitchen_lst.configure(background="white")
        self.kitchen_lst.configure(disabledforeground="#a3a3a3")
        self.kitchen_lst.configure(font="-family {Tahoma} -size 10")
        self.kitchen_lst.configure(foreground="#ff8000")
        self.kitchen_lst.configure(highlightbackground="#d9d9d9")
        self.kitchen_lst.configure(highlightcolor="black")
        self.kitchen_lst.configure(selectbackground="#c4c4c4")
        self.kitchen_lst.configure(selectforeground="black")

        self.Label1_2 = tk.Label(top)
        self.Label1_2.place(relx=0.13, rely=0.383, height=22, width=152)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="#000000")
        self.Label1_2.configure(background="#d9d9d9")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font="-family {Segoe Print} -size 13")
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''In kitchen''')

        self.done_lst = tk.Listbox(top)
        self.done_lst.place(relx=0.4, rely=0.2, relheight=0.5
                            , relwidth=0.3)
        self.done_lst.configure(background="white")
        self.done_lst.configure(disabledforeground="#a3a3a3")
        self.done_lst.configure(font="-family {Tahoma} -size 10")
        self.done_lst.configure(foreground="#009900")
        self.done_lst.configure(highlightbackground="#d9d9d9")
        self.done_lst.configure(highlightcolor="black")
        self.done_lst.configure(selectbackground="#c4c4c4")
        self.done_lst.configure(selectforeground="black")

        self.Label1_3 = tk.Label(top)
        self.Label1_3.place(relx=0.5, rely=0.16, height=21, width=152)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="#000000")
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font="-family {Segoe Print} -size 13")
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Done''')


def show(server):
    return vp_start_gui(server)
